### ISSUE TITLE
Add chain rule

### ISSUE THREAD

**Issue by sophiefisher** [JuliaMath/FastChebInterp.jl#8]
Please add a chain rule support for differentiating the chebyshev polynomial
```
function rrule(c::ChebPoly, x::Real)
    project_x = ProjectTo(x)
    y, Δy = chebgradient(c, x)
    pullback(∂y) = NoTangent(), project_x(Δy' * ∂y)
    y, pullback
end
```

**Comment by stevengj** [comment]
Should be fixed by #9.

Note that `NoTangent()` here is incorrect — the first argument here should, in principle, be a `Tangent` object representing the sensitivity to the data *inside* the `ChebPoly` object (the polynomial coefficients and the bounds).   However, this is huge object (because of the huge number of coefficients) that doesn't seem worthwhile to compute, so the correct thing to do is to mark it as `@notimplemented` rather than returning an incorrect result (`NoTangent` represents a zero derivative).
